### ISSUE TITLE
Some emails being sent from open-wide are flagged as suspicious

### ISSUE THREAD

**Issue by vimto** [the-open/lumen#8]
Here is the original error report:

> I get this warning whenever I get an email sent through open-wide. I just saw this on the email from aurora on the commons website intro email. I am not sure if this is something to worry about or if only I get these warnings, but am wondering if this would be a deterrent for people, and they may not want to click on the links?
> ![image](https://user-images.githubusercontent.com/63005/52376502-263e8200-2ac7-11e9-93c7-dc0809ef499c.png)

cc @michaelsnook @hiemanshu

**Comment by vimto** [comment]
Hey, just had a quick look into this. A few notes/observations:

- Here is the code that sets up the from/reply-to/sender headers:
https://github.com/the-open/lumen/blob/master/models/conversation_post_bcc.rb#L67: 
```ruby
mail = Mail.new
mail.to = group.email
if Config['REPLY_TO_GROUP']
  mail.reply_to = group.email
end
mail.from = "#{conversation_post.account.name} <#{conversation_post.from_address}>"
mail.sender = group.email('-noreply')
mail.subject = conversation.visible_conversation_posts.count == 1 ? "[#{group.slug}] #{conversation.subject}" : "Re: [#{group.slug}] #{conversation.subject}"
mail.headers({
    'Precedence' => 'list',
    'X-Auto-Response-Suppress' => 'OOF',
    'Auto-Submitted' => 'auto-generated',
    'List-Id' => "<#{group.slug}.list-id.#{Config['MAIL_DOMAIN']}>",
    'List-Unsubscribe' => "<http://#{Config['MAIL_DOMAIN']}/groups/#{group.slug}/notification_level?level=none>"
  })
```

- And here is what determines `conversation_post.from_address`: https://github.com/the-open/lumen/blob/master/models/conversation_post.rb#L107
```ruby
def from_address
  group = conversation.group
  from = account.email
  if Config['HIDE_ACCOUNT_EMAIL']
    group.email
  elsif ConversationPost.dmarc_fail_domains.include?(from.split('@').last)
    group.email('-noreply')
  else
    from
  end
end
```

- From a little research, it is OK to have different from, sender and reply-to email domains. **But** they both need to be authorised via DKIM/SPF

- Looking at the code, in some cases the from header (returned from the `from_address` method) can be set to the individuals email address.(`account.email`). If this is a domain other than open-wide.net, the email would be suspicious since we only have SPF in place for open-wide.net.

- The reply-to header overrides the from when replying in an email client. In the code above the logic for setting the two are separate which looks like it leads to buggy behaviour: if `Config['REPLY_TO_GROUP']` to falsey, but Config['HIDE_ACCOUNT_EMAIL'] is truthy, the from header is set to `group.email` enabling the reply-to-group functionality anyway.

- Also, looking at some example open-wide emails I've received from tech/tech-leads/identity-dev groups, the `reply_to` header is _not_ set. So when I hit reply it defaults to the from header (the individual) so the _Respond by replying above this line_ feature is broken

- Finally, I don't think we need to explicitly set the sender header at all, since it can be inferred. And inspecting the headers of some other example lists (E.g. GitHub issue notifications, Google Calendar notifications) it is not used.

So I think we could:
1. Change the `from_address` method to always return `group.email('-noreply')`
2. Remove the `mail.sender = group.email('-noreply')` line
3. Double check the Config['REPLY_TO_GROUP'] flag for the different groups that are sending to ensure reply-to is being set properly.

Thoughts?

**Comment by michaelsnook** [comment]
Strange! I just went and checked and reply-to-group is false right now... I thought we had set that to true a long time ago and it seems to be the way things behave... I just changed it to true, and then to false, and sent another test email, and still it seems to reply to group despite that config variable being false...

And I can't figure out, why is the `from_address` using this no-reply? AFAICT the no-reply is only needed for the return path, and when reply-to-group is set we should use group address for reply-to, and use the user's email for the from and sender address. 

Either way it sounds like we should set up DKIM? But I'm inspecting this test email and it appears DKIM is passing...

```
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@open-wide.net header.s=mail header.b="hw/kSuyD";
       spf=pass (google.com: domain of testing123-noreply@open-wide.net designates 
       146.185.137.156 as permitted sender)
```

So I'm confused on this point too.

**Comment by vimto** [comment]
The setting of `reply_to` and `from` are based on separate logic and flags, which looks like it leads to the weird behavior you are seeing. E.g. even of `REPLY_TO_GROUP` is false, `from` is set to the group email if `HIDE_ACCOUNT_EMAIL` is true.

I don't think we can/should set the from header to the senders real email address - as I understand, having that set to a non `open-wide.net` domain is what is causing the issue; and it's not feasible to authenticate all possible different domains this could take.

Hence the suggestion of _always_ setting from to be set to `group.email('-noreply')` (which will be a an `open-wide.net` domain), leaving code in place to set reply-to to `group.email` if `Config['REPLY_TO_GROUP']` is true, and double checking this value is set correctly for all groups.

Anything to chime in with here @hiemanshu?
